import { createEnv } from '@t3-oss/env-core'
import { z } from 'zod'

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    BETTER_AUTH_SECRET: z.string().min(1),
    BETTER_AUTH_URL: z.string().url(),
    SOLARI_API_KEY: z.string().min(1),
    SOLARI_PROFILE_ID: z.string().min(1),
    PLATFORM_CARD_NUMBER: z.string().min(1),
    PLATFORM_CARD_EXPIRY: z.string().min(1),
    PLATFORM_CARD_CVV: z.string().min(1),
    QUICKCOMMERCE_API_KEY: z.string().min(1),
    RESEND_API_KEY: z.string().min(1),
    DODO_PAYMENTS_API_KEY: z.string().min(1),
    DODO_PAYMENTS_WEBHOOK_KEY: z.string().min(1),
    DODO_PAYMENTS_ENVIRONMENT: z.enum(['test_mode', 'live_mode']).default('test_mode'),
    DODO_PAYMENTS_WALLET_PRODUCT_ID: z.string().min(1),
    SENTRY_AUTH_TOKEN: z.string().optional(),
  },
  clientPrefix: 'VITE_',
  client: {
    VITE_SENTRY_DSN: z.string().optional(),
    VITE_SENTRY_ORG: z.string().optional(),
    VITE_SENTRY_PROJECT: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    BETTER_AUTH_SECRET: process.env.BETTER_AUTH_SECRET,
    BETTER_AUTH_URL: process.env.BETTER_AUTH_URL,
    SOLARI_API_KEY: process.env.SOLARI_API_KEY,
    SOLARI_PROFILE_ID: process.env.SOLARI_PROFILE_ID ?? process.env.INSTAMART_PROFILE_ID ?? process.env.FLIPKART_PROFILE_ID,
    PLATFORM_CARD_NUMBER: process.env.PLATFORM_CARD_NUMBER,
    PLATFORM_CARD_EXPIRY: process.env.PLATFORM_CARD_EXPIRY,
    PLATFORM_CARD_CVV: process.env.PLATFORM_CARD_CVV,
    QUICKCOMMERCE_API_KEY: process.env.QUICKCOMMERCE_API_KEY,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    DODO_PAYMENTS_API_KEY: process.env.DODO_PAYMENTS_API_KEY,
    DODO_PAYMENTS_WEBHOOK_KEY: process.env.DODO_PAYMENTS_WEBHOOK_KEY,
    DODO_PAYMENTS_ENVIRONMENT: process.env.DODO_PAYMENTS_ENVIRONMENT,
    DODO_PAYMENTS_WALLET_PRODUCT_ID: process.env.DODO_PAYMENTS_WALLET_PRODUCT_ID,
    SENTRY_AUTH_TOKEN: process.env.SENTRY_AUTH_TOKEN,
    VITE_SENTRY_DSN: import.meta.env.VITE_SENTRY_DSN,
    VITE_SENTRY_ORG: import.meta.env.VITE_SENTRY_ORG,
    VITE_SENTRY_PROJECT: import.meta.env.VITE_SENTRY_PROJECT,
  },
  emptyStringAsUndefined: true,
})
